#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

key=$(ynh_string_random --length=32)
ynh_app_setting_set --key=key --value=$key

# Configure redis
redis_activity_db=$(ynh_redis_get_free_db)
ynh_app_setting_set --key=redis_activity_db --value="$redis_activity_db"

redis_broker_db=$(ynh_redis_get_free_db)
ynh_app_setting_set --key=redis_broker_db --value="$redis_broker_db"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir" --source_id="main"
ynh_setup_source --dest_dir="$install_dir/static/fonts/source_han_sans" --source_id="fonts"

#=================================================
# CONFIGURE THEN INSTALL SCRIPT AND DEPENDENCIES
#=================================================
ynh_script_progression "Installing service script..."

ynh_config_add --template=".env.production" --destination="$install_dir/.env"

mkdir "$install_dir/venv"
python3 -m venv "$install_dir/venv"
$install_dir/venv/bin/pip3 install -r "$install_dir/requirements.txt"

#=================================================
# INITIALIZE DATABASE
#=================================================
ynh_script_progression "Initializing database..."

ynh_psql_db_shell <<< "CREATE EXTENSION IF NOT Exists pg_trgm;"

pushd $install_dir
	$install_dir/venv/bin/python3 "$install_dir/manage.py" migrate
	$install_dir/venv/bin/python3 "$install_dir/manage.py" initdb
	$install_dir/venv/bin/python3 "$install_dir/manage.py" compile_themes
	$install_dir/venv/bin/python3 "$install_dir/manage.py" collectstatic --no-input
popd

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_logrotate

ynh_exec_as_app touch /var/log/$app/$app.log
ynh_exec_as_app touch /var/log/$app/$app-beat.log
ynh_exec_as_app touch /var/log/$app/$app-worker.log

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression "Configuring $app's systemd service..."

ynh_config_add --template="bookwyrm.target" --destination="/etc/systemd/system/$app.target"

ynh_config_add_systemd --service="$app-server" --template="bookwyrm-server.service"
ynh_config_add_systemd --service="$app-worker" --template="bookwyrm-worker.service"
ynh_config_add_systemd --service="$app-beat"   --template="bookwyrm-beat.service"

yunohost service add "$app-beat" --log="/var/log/$app/$app-beat.log"
yunohost service add "$app-server" --log="/var/log/$app/$app.log"
yunohost service add "$app-worker" --log="/var/log/$app/$app-worker.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app-beat" --action="start" --log_path="systemd" --wait_until="Started bookwyrm celery beat process"
ynh_systemctl --service="$app-server" --action="start" --log_path="systemd" --wait_until="Booting worker with pid"
ynh_systemctl --service="$app-worker" --action="start" --log_path="systemd" --wait_until="ready"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
