#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers


#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_exec_warn_less yunohost service status "${app}-server" >/dev/null
then
	ynh_script_progression --message="Removing ${app}-server service integration..."
	yunohost service remove "${app}-server"
fi

if ynh_exec_warn_less yunohost service status "${app}-worker" >/dev/null
then
	ynh_script_progression --message="Removing ${app}-worker service integration..."
	yunohost service remove "${app}-worker"
fi

if ynh_exec_warn_less yunohost service status "${app}-beat" >/dev/null
then
	ynh_script_progression --message="Removing ${app}-beat service integration..."
	yunohost service remove "${app}-beat"
fi

#=================================================
# STOP AND REMOVE SERVICE
#=================================================
ynh_script_progression --message="Stopping and removing the systemd service..." --weight=1

ynh_systemd_action --service_name="$app-beat" --action="stop" --log_path="systemd" --line_match="Stopped $app"
ynh_systemd_action --service_name="$app-server" --action="stop" --log_path="systemd" --line_match="Stopped $app"
ynh_systemd_action --service_name="$app-worker" --action="stop" --log_path="systemd" --line_match="Stopped $app"

# Remove the dedicated systemd config
ynh_remove_systemd_config --service="$app-beat" --log="/var/log/$app/$app-beat.log"
ynh_remove_systemd_config --service="$app-server" --log="/var/log/$app/$app.log"
ynh_remove_systemd_config --service="$app-worker" --log="/var/log/$app/$app-worker.log"

ynh_secure_remove --file="/etc/systemd/system/$app.target"

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Removing NGINX web server configuration..." --weight=1

# Remove the dedicated NGINX config
ynh_remove_nginx_config

#=================================================
# REMOVE LOGS
#=================================================
ynh_script_progression --message="Removing logs..."  --weight=5

ynh_remove_logrotate

# Remove the log files
ynh_secure_remove --file="/var/log/$app"


#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
