#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

if ynh_hide_warnings yunohost service status "$app-server" >/dev/null; then
	yunohost service remove "$app-server"
fi

if ynh_hide_warnings yunohost service status "$app-worker" >/dev/null; then
	yunohost service remove "$app-worker"
fi

if ynh_hide_warnings yunohost service status "$app-beat" >/dev/null; then
	yunohost service remove "$app-beat"
fi

ynh_systemctl --service="$app-beat" --action="stop" --log_path="systemd" --wait_until="Stopped $app"
ynh_systemctl --service="$app-server" --action="stop" --log_path="systemd" --wait_until="Stopped $app"
ynh_systemctl --service="$app-worker" --action="stop" --log_path="systemd" --wait_until="Stopped $app"

ynh_config_remove_systemd"$app-beat"
ynh_config_remove_systemd"$app-server"
ynh_config_remove_systemd"$app-worker"

ynh_safe_rm "/etc/systemd/system/$app.target"

ynh_config_remove_nginx

ynh_config_remove_logrotate

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
