#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app-server" >/dev/null
then
	ynh_script_progression "Removing $app-server service integration..."
	yunohost service remove "$app-server"
fi

if ynh_hide_warnings yunohost service status "$app-worker" >/dev/null
then
	ynh_script_progression "Removing $app-worker service integration..."
	yunohost service remove "$app-worker"
fi

if ynh_hide_warnings yunohost service status "$app-beat" >/dev/null
then
	ynh_script_progression "Removing $app-beat service integration..."
	yunohost service remove "$app-beat"
fi

#=================================================
# STOP AND REMOVE SERVICE
#=================================================
ynh_script_progression "Stopping and removing the systemd service..."

ynh_systemctl --service="$app-beat" --action="stop" --log_path="systemd" --wait_until="Stopped $app"
ynh_systemctl --service="$app-server" --action="stop" --log_path="systemd" --wait_until="Stopped $app"
ynh_systemctl --service="$app-worker" --action="stop" --log_path="systemd" --wait_until="Stopped $app"

# Remove the dedicated systemd config
ynh_config_remove_systemd"$app-beat"
ynh_config_remove_systemd"$app-server"
ynh_config_remove_systemd"$app-worker"

ynh_safe_rm "/etc/systemd/system/$app.target"

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Removing NGINX web server configuration..."

# Remove the dedicated NGINX config
ynh_config_remove_nginx

#=================================================
# REMOVE LOGS
#=================================================
ynh_script_progression "Removing logs..."

ynh_config_remove_logrotate

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
