#!/bin/bash


source /usr/share/yunohost/helpers

db_name=$(ynh_app_setting_get --key=db_name)

# Configure redis
redis_activity_db=$(ynh_redis_get_free_db)
ynh_app_setting_set --key=redis_activity_db --value="$redis_activity_db"

redis_broker_db=$(ynh_redis_get_free_db)
ynh_app_setting_set --key=redis_broker_db --value="$redis_broker_db"

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

# reapply config with new Redis configuration
ynh_config_add --template=".env.production" --destination="$install_dir/.env"

#=================================================
# RESTORE THE POSTGRESQL DATABASE
#=================================================
ynh_script_progression "Restoring the PostgreSQL database..."

ynh_psql_db_shell < ./db.sql

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/systemd/system/bookwyrm-beat.service"
ynh_restore "/etc/systemd/system/bookwyrm-server.service"
ynh_restore "/etc/systemd/system/bookwyrm-worker.service"
ynh_restore "/etc/systemd/system/bookwyrm.target"

systemctl enable "bookwyrm-beat.service" --quiet
systemctl enable "bookwyrm-server.service" --quiet
systemctl enable "bookwyrm-worker.service" --quiet

yunohost service add "$app-beat" --log="/var/log/$app/$app-beat.log"
yunohost service add "$app-server" --log="/var/log/$app/$app.log"
yunohost service add "$app-worker" --log="/var/log/$app/$app-worker.log"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service="$app-beat" --action="start" --log_path="systemd" --wait_until="Started bookwyrm-beat.service"
ynh_systemctl --service="$app-server" --action="start" --log_path="systemd" --wait_until="Booting worker with pid"
ynh_systemctl --service="$app-worker" --action="start" --log_path="systemd" --wait_until="ready"

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
