#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

# uncomment me after some updates whenever the key variable is set in install for some times
#key=$(ynh_app_setting_get --key=key --value=$key)

#remove me when key setting is uncommented (see above)
key=$(ynh_string_random --length=32)

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --action="stop" --service="bookwyrm-beat" --log_path="systemd"
ynh_systemctl --action="stop" --service="bookwyrm-server" --log_path="systemd"
ynh_systemctl --action="stop" --service="bookwyrm-worker" --log_path="systemd"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

# FIXME: this is still supported but the recommendation is now to *always* re-setup the app sources wether or not the upstream sources changed
if ynh_app_upstream_version_changed
then
	ynh_script_progression "Upgrading source files..."

	# Download, check integrity, uncompress and patch the source from app.src
	ynh_setup_source --dest_dir="$install_dir" --source_id="main" --full_replace --keep=".env"
	ynh_setup_source --dest_dir="$install_dir/static/fonts/source_han_sans" --source_id="fonts" --full_replace
fi

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 750 "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod -R o-rwx "$install_dir"
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app:www-data "$install_dir"
#=================================================
# CONFIGURE THE INSTALL SCRIPT
#=================================================
ynh_script_progression "Upgrading .env file..."

ynh_config_add --template=".env.production" --destination="$install_dir/.env"
#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 600 $install_dir/.env
#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown $app: "$install_dir/.env"

#=================================================
# CONFIGURE THEN INSTALL SCRIPT AND DEPENDENCIES
#=================================================
ynh_script_progression "Installing service script..."

ynh_safe_rm "$install_dir/venv"
mkdir "$install_dir/venv"
python3 -m venv "$install_dir/venv"
$install_dir/venv/bin/pip3 install -r "$install_dir/requirements.txt"

#=================================================
# Update DATABASE
#=================================================
ynh_script_progression "Upgrading database..."

pushd $install_dir
$install_dir/venv/bin/python3 "$install_dir/manage.py" compile_themes
$install_dir/venv/bin/python3 "$install_dir/manage.py" collectstatic --no-input
$install_dir/venv/bin/python3 "$install_dir/manage.py" makemigrations --merge --no-input
$install_dir/venv/bin/python3 "$install_dir/manage.py" migrate
popd

#=================================================
# SET PERMISSIONS ON BOOKWYRM DIRECTORY
#=================================================

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app:www-data $install_dir
#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Upgrading NGINX web server configuration..."

# Create a dedicated NGINX config
ynh_config_add_nginx

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression "Upgrading systemd configuration..."

ynh_config_add --template="bookwyrm.target" --destination="/etc/systemd/system/$app.target"

# Create a dedicated systemd config
ynh_config_add_systemd --service="$app-server" --template="bookwyrm-server.service"
ynh_config_add_systemd --service="$app-worker" --template="bookwyrm-worker.service"
ynh_config_add_systemd --service="$app-beat"   --template="bookwyrm-beat.service"

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression "Integrating service in YunoHost..."

yunohost service add "$app-beat" --log="/var/log/$app/$app-beat.log"
yunohost service add "$app-server" --log="/var/log/$app/$app.log"
yunohost service add "$app-worker" --log="/var/log/$app/$app-worker.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app-beat" --action="start" --log_path="systemd" --wait_until="Started bookwyrm celery beat process"
ynh_systemctl --service="$app-server" --action="start" --log_path="systemd" --wait_until="Booting worker with pid"
ynh_systemctl --service="$app-worker" --action="start" --log_path="systemd" --wait_until="ready"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
